apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f combined-worker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: corda
  name: corda
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "7004"
      port: 7004
      targetPort: 7004
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: corda
