apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f combined-worker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: flow-management-tool
  name: flow-management-tool
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: flow-management-tool
